url: maciejzok.pl

permalink: none
slugify: latin

timezone: Europe/Warsaw

sass:
    sourcemap: true
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "essay"
